<?php

require_once('dbh.php');
require_once('session.php');
$outlets = array(array());
$employees = $_POST['username'];
$projectname = $_POST['projectname'];
$startdate = $_POST['startdate'];
$subdate = $_POST['enddate'];
$priority = $_POST['projetpriority'];
$outlets = ($_POST['outlets'] != null) ? $_POST['outlets'] : array(array());

$sql = "";
foreach ($projectname as $key1 => $pname) {
	$taskDetail = addslashes($pname);
	foreach ($employees as $key => $employee) {
		$employeeID = explode(" ", $employees[$key]);
		if ($outlets != null) {
			if (array_key_exists('Task' . $key1, $outlets)) {
				foreach ($outlets["Task" . $key1] as $key2 => $outlet) {
					$outletid = $outlets["Task" . $key1][$key2];
					$IdName = explode("_", $outletid);
					$ID = $IdName[0];
					$Name = $IdName[1];
					$sql .= " INSERT INTO `project`(`u_id`, `proof_img`, `pname`, `startdate` , `duedate`, `priority` , `status`, `outlet_id`, `outlet_name`, `assige_by`) VALUES ('$employeeID[0]', 'No.png',  '$taskDetail', '$startdate[$key1]', '$subdate[$key1]', '$priority[$key1]', 'Due', '$ID', '$Name', '" . $_SESSION['id'] . "'); \n";

					$to = $employeeID[2];
					$data = array(
						'title' => 'Task',
						'body' => $Name . " : " . $taskDetail,
						'icon' => '../assets/images/AD2.png'
					);

					$toweb = $employeeID[1];
					$dataweb = array(
						'title' => 'Task',
						'body' => $Name . " : " . $taskDetail,
						'icon' => '../assets/images/AD2.png'
					);

					notify($to, $data);
					sendNotification($toweb, $dataweb);
				}
			} else {
				$ID = 0;
				$Name = "Reguler";
				$sql .= " INSERT INTO `project`(`u_id`, `proof_img`, `pname`, `startdate` , `duedate`, `priority` , `status`, `outlet_id`, `outlet_name`, `assige_by`) VALUES ('$employeeID[0]', 'No.png',  '$taskDetail', '$startdate[$key1]', '$subdate[$key1]', '$priority[$key1]', 'Due', '$ID', '$Name', '" . $_SESSION['id'] . "'); \n";

				$to = $employeeID[2];
				$data = array(
					'title' => 'Task',
					'body' => $Name . " : " . $taskDetail,
					'icon' => '../assets/images/AD2.png'
				);

				$toweb = $employeeID[1];
				$dataweb = array(
					'title' => 'Task',
					'body' => $Name . " : " . $taskDetail,
					'icon' => '../assets/images/AD2.png'
				);

				notify($to, $data);
				sendNotification($toweb, $dataweb);
			}
		}
	}
}

echo nl2br($sql);

if (mysqli_multi_query($conn, $sql)) {
	$_SESSION['status'] = "Added Successfully";
	$_SESSION['status_code'] = "success";
	header("Location:../assignproject.php");
} else {
	$_SESSION['status'] = "Not Added Successfully";
	$_SESSION['status_code'] = "error";
	header("Location:../assignproject.php");
}

function notify($to, $data)
{
	$api_key = "AAAA2thubTE:APA91bHz1oyOuLpIvoA9soXqoAT7Dsy-3O9TtlR4FyZni7PFZrr3rfM7j4WlrMKUQRcl9-jmjWEkQudLTuQWc75MFsg-h6vrRMCZ4H6j_ds5p77nuFMJQDj1EuofT2KFXZjPrYSaldiw";
	$url = "https://fcm.googleapis.com/fcm/send";
	$fields = array('to' => $to, 'notification' => $data);

	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();

	curl_setopt($ch, CURLOPT_URL, $url);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_POST, 1);
	curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($fields));

	$headers = array();
	$headers[] = 'Authorization: key =' . $api_key;
	$headers[] = 'Content-Type: application/json';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

	$result = curl_exec($ch);
	if (curl_errno($ch)) {
		echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);
}

function sendNotification($toweb, $dataweb)
{
	$url = "https://fcm.googleapis.com/fcm/send";

	$fields = array('to' => $toweb, 'notification' => $dataweb);

	$headers = array(
		'Authorization: key=AAAA2thubTE:APA91bHz1oyOuLpIvoA9soXqoAT7Dsy-3O9TtlR4FyZni7PFZrr3rfM7j4WlrMKUQRcl9-jmjWEkQudLTuQWc75MFsg-h6vrRMCZ4H6j_ds5p77nuFMJQDj1EuofT2KFXZjPrYSaldiw',
		'Content-Type:application/json'
	);
	// print_r($fields);

	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, $url);
	curl_setopt($ch, CURLOPT_POST, true);
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($fields));
	$result = curl_exec($ch);
	print_r($result);
	curl_close($ch);
}
