<?php

require_once ('../process/dbh.php');
require_once ('../session.php');

$pname = $_POST['projectname'];
$eid = $_POST['username'];
$startdate = $_POST['startdate'];
$subdate = $_POST['enddate'];
$priority = $_POST['projetpriority'];

function notify($to,$data){
	$api_key="AAAA2thubTE:APA91bHz1oyOuLpIvoA9soXqoAT7Dsy-3O9TtlR4FyZni7PFZrr3rfM7j4WlrMKUQRcl9-jmjWEkQudLTuQWc75MFsg-h6vrRMCZ4H6j_ds5p77nuFMJQDj1EuofT2KFXZjPrYSaldiw";
	$url="https://fcm.googleapis.com/fcm/send";
	$fields=json_encode(array('to'=>$to,'notification'=>$data));

	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();

	curl_setopt($ch, CURLOPT_URL, $url);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_POST, 1);
	curl_setopt($ch, CURLOPT_POSTFIELDS, ($fields));

	$headers = array();
	$headers[] = 'Authorization: key ='.$api_key;
	$headers[] = 'Content-Type: application/json';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

	$result = curl_exec($ch);
	if (curl_errno($ch)) {
		echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);
}

function sendNotification($toweb,$dataweb){
	$url ="https://fcm.googleapis.com/fcm/send";

	$fields=array('to'=>$toweb,'notification'=>$dataweb);

	$headers=array(
		'Authorization: key=AAAA2thubTE:APA91bHz1oyOuLpIvoA9soXqoAT7Dsy-3O9TtlR4FyZni7PFZrr3rfM7j4WlrMKUQRcl9-jmjWEkQudLTuQWc75MFsg-h6vrRMCZ4H6j_ds5p77nuFMJQDj1EuofT2KFXZjPrYSaldiw',
		'Content-Type:application/json'
	);

	$ch=curl_init();
	curl_setopt($ch,CURLOPT_URL,$url);
	curl_setopt($ch,CURLOPT_POST,true);
	curl_setopt($ch,CURLOPT_HTTPHEADER,$headers);
	curl_setopt($ch,CURLOPT_RETURNTRANSFER,true);
	curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($fields));
	$result=curl_exec($ch);
	print_r($result);
	curl_close($ch);
}

	

$j = count($eid);
for($i = 0; $i < $j ; $i++) {
	echo $eid[$i]."<br><br>";
	$pieces = explode(" ", $eid[$i]);
	echo $pieces[0]."<br><br>"; // piece1
	echo $pieces[1]."<br><br>"; // piece2
	echo $pieces[2]."<br><br>"; // piece2
	
	$to=$pieces[2];
	$data=array(
		'title'=>'Task',
		'body'=> $pname,
		'icon'=>'../assets/images/AD2.png'
	);
	
	$toweb=$pieces[1];
	$dataweb=array(
		'title'=>'Task',
		'body'=> $pname,
		'icon'=>'../assets/images/AD2.png'
	);
	
	$sql = "INSERT INTO `project`(`u_id`, `proof_img`, `pname`, `startdate` , `duedate`, `priority` , `status`,`assige_by`) VALUES ('$pieces[0]', 'No.png',  '$pname', '$startdate', '$subdate', '$priority' , 'Due', '".$_SESSION['id']."')";
	$result = mysqli_query($conn, $sql);
	
	if(($result) == 1){
		notify($to,$data);
		sendNotification($toweb,$dataweb);
		$_SESSION['status'] = "Added Successfully";
		$_SESSION['status_code'] = "success";
	}
	else{
		$_SESSION['status'] = "Not Added Successfully";
		$_SESSION['status_code'] = "error";
	}	
}

header("Location:../assignproject.php");

?>